[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts","@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/"]
# The remappings above are used to map the OpenZeppelin contracts to the local path

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
